### PR TITLE
Changes related to fixing redirect paths & custom auth for embedded s…

### PR DESCRIPTION
**Pull request by vishalshrm539**
…cenarios

### CODE REVIEW

**Review by JEAxero — APPROVED** [review]
Looks good.

**Comment by JEAxero** [comment]
@vishalshrm539 Note that you'll need to get this branch updated with the current "main" to this PR to be able to merge. (Forgot to mention that in my PR approval.)

**Comment by vishalshrm539** [comment]
> @vishalshrm539 Note that you'll need to get this branch updated with the current "main" to this PR to be able to merge. (Forgot to mention that in my PR approval.)

Yes John, did similar thing in Angular SDK as well.

**Comment by JEAxero** [comment]
@vishalshrm539 Any reason why this change never got merged?

**Comment by vishalshrm539** [comment]
> @vishalshrm539 Any reason why this change never got merged?

Should have been merged, I just forgot about this PR. Sorry for the delay.

**Comment by JEAxero** [comment]
> > @vishalshrm539 Any reason why this change never got merged?
> 
> Should have been merged, I just forgot about this PR. Sorry for the delay.

No problem. Just wanted to make sure it was done (if still intended) or marked as "not to merge" if there was a change in plan. Thanks!

**Pull request merged**
